version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd Angular
      - echo Installing source NPM dependencies...
      - npm install -y npm@latest
      - npm install -g @angular/cli
      - rm package-lock.json
      - cd ..
  pre_build:
    commands:
      - cd Angular
      - echo Installing source NPM dependencies
      - npm install 
      - npm install -g @angular/cli
      - cd ..
  build:
    commands:
      - cd Angular
      - echo Build started on `date`
      - ng build
  
artifacts:
  files:
    - 'dist/smart-shoppers/**'
    - 'package.json'
    - 'server.js'
    - 'cert.pem'
    - 'key.pem'
  discard-paths: yes
  base-directory: 'Angular'
