version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd Angular
      - echo Installing source NPM dependencies
      - npm install --save-dev @angular-devkit/build-angular
      - npm install 
      - npm install -g @angular/cli@latest
      - cd ..
  build:
    commands:
      - cd Angular
      - echo Build started on `date`
      - ng build
  
artifacts:
  files:
    - 'dist/smart-shoppers/*'
    - 'package.json'
    - 'server.js'
    - 'cert.pem'
    - 'key.pem'
  # discard-paths: yes
  base-directory: 'Angular'
