version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - echo change to Angular directory 
      - cd Angular 
      - echo Installing source NPM dependencies
      - npm install 
      - npm install -g @angular/cli
      - echo change to root directory 
      - cd .. 
  build:
    commands:
      - cd Angular
      - echo Build started on `date`
      # - ng build --prod --aot
      - ng build
  
artifacts:
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.ico'
  discard-paths: yes
  base-directory: 'Angular/dist/smart-shoppers'
